### PR TITLE
Improvements and new features

### PR DESCRIPTION
**Pull request by ideas-into-software**
Hi, 

I wanted to share with you this code I committed yesterday, which is improving on your work in several ways. 

I already started using this new version (e.g. in https://github.com/ideas-into-software/automated-linguistic-analysis). I also wanted to use this updated version for my clients without going through the hassle of installing it manually, therefore I'm submitting this pull request. 

Hopefully this can be of use to you as well. 

Kind regards,
Michal

### CODE REVIEW

**Review by phillip-kruger — APPROVED** [review]

**Comment by phillip-kruger** [comment]
Thanks ! LGTM.

**Comment by deanjameseverett** [comment]
Hi Michal

Thanks for the contribution. Will check it out. Phillip has already merged
the changes into Master.

Regards
Dean James-Everett

**Comment by ideas-into-software** [comment]
Hi, 

That was quick! I noticed latest release available in Maven Repository is 1.0.3 (https://mvnrepository.com/artifact/com.github.deanjameseverett/k8-maven-plugin). 

If it's not a lot of work - and if it is beyond what you can schedule for now, perhaps I can help with this - is it possible to cut a release for this 1.0.5 version and push it to https://mvnrepository.com/artifact/com.github.deanjameseverett/k8-maven-plugin ? 

Kind regards,

**Comment by deanjameseverett** [comment]
Hi Michal

That would be great. What assistance do you need?

Regards Dean James-Everett

**Comment by ideas-into-software** [comment]
Hi Dean,

I wasn't able to follow up on this earlier. 

Since you already made a release to Maven Central and 'com.github.deanjameseverett' group is already approved and linked to your account only (https://issues.sonatype.org/browse/OSSRH-33891) I would not be able to make the 1.0.5 release to https://mvnrepository.com/artifact/com.github.deanjameseverett/k8-maven-plugin

Workaround would be to: 

 1) add my 'mhs' Sonatype Jira account (https://issues.sonatype.org/secure/ViewProfile.jspa?name=mhs) to list of usernames approved to deploy artifacts to this groupId (see 'Username(s)' field @ https://issues.sonatype.org/browse/OSSRH-33891, which currently lists your username only, i.e. 'gracewell'), AND 

 2) add my 'ideas-into-software' Github account (https://github.com/ideas-into-software) as collaborator on the https://github.com/deanjameseverett/k8-maven-plugin project


Please let me know your decision / if the above is feasible, otherwise it's only you who can publish this new release to Maven Central. 

Kind regards,

**Comment by ideas-into-software** [comment]
Hi, 

Kindly please let me know the status of this, i.e. whether you can make these changes I mentioned so I can push these myself. 

I understand you might not have the time, but I cannot push this myself as of now due to what I mentioned earlier (2+ weeks ago) and since I'm only contributing to this project I would rather not release this under my group ID (so as to work around these restrictions), unless that's what you prefer.

Regards,

**Pull request merged**
